FROM golang:latest as builder

COPY . /
WORKDIR /
ENV GO111MODULE=on
RUN CGO_ENABLED=0 GOOOS=linux go build -o serverexec ./main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder / .
CMD ["./serverexec"]